### PR TITLE
Added new map

### PR DESCRIPTION
**Pull request by Snorps**
hopefully this works :x

### CODE REVIEW

**Comment by Restioson** [comment]
Thanks so much for the PR, I can check tomorrow to test

**Review by gegy1000 — APPROVED** [review]

**Comment by Restioson** [comment]
Might be good to add a game config that uses this map. Is there any particular mode / settings that the map should be played with? E.g winner takes all, with a knockback stick, point based...

**Comment by Snorps** [comment]
oh! i didn't even think of that. im not sure what point based means but a knockback stick would definitely be good. ill go see if i can figure out how game configs work

**Comment by Snorps** [comment]
something like this? idk what spawn_angle does :x

**Comment by Snorps** [comment]
exactly what it sounds like it turns out probably! :p

**Comment by Restioson** [comment]
Point based means that being on the throne gives the player points, as opposed to in winner takes all when whoever is the last one on the throne is the winner. Spawn angle just sets the angle the player is facing when they spawn. In game if you press f3 you can get the angle for any direction. It's just there so you don't spawn looking away from the map

**Comment by Snorps** [comment]
Cool! Everything on the game config is set up how we want it now

**Comment by Restioson** [comment]
Thanks!

**Pull request merged**
