### PR TITLE
Blommor map

### PR DESCRIPTION
**Pull request by sockfriends**
did i do this right

### CODE REVIEW

**Comment by Restioson** [comment]
There are some conflicts to resolve

**Comment by Restioson** [comment]
Just reminding that there are still conflicts but i'm not sure if it was merged in another PR?

**Comment by sockfriends** [comment]
i dont have write access

**Comment by Restioson** [comment]
You do, it's your own fork

**Comment by sockfriends** [comment]
well it says i dont

**Comment by Restioson** [comment]
I don't know how to help you because the conflicts need to be resolved on your side since they come from your branch of your fork; what are you doing that tells you that you don't have permission? You definitely have permission to push to sockfriends/koth:blommer-map

**Comment by sockfriends** [comment]
Screenshot (1066)

**Comment by Restioson** [comment]
The reason that is greyed out is because the conflicts are too complex to be resolved in the web UI, not because you don't have permission - it's also greyed out for me.

**Comment by sockfriends** [comment]
oh ok

**Comment by Restioson** [comment]
Was merged already i believe

**Pull request closed without merging**
