### PR TITLE
Fix this comma that broke entire koth

### PR DESCRIPTION
**Pull request by moehreag**
I didn't put it in so I now have to

### CODE REVIEW

**Comment by Restioson** [comment]
This has merge conflicts

**Comment by Restioson** [comment]
Also, what comma is this referring to? There is no comma error that this fixes according to the diff.

**Comment by moehreag** [comment]
The diff sadly doesn't show it.. It was here:   "time": 12300 **,** "players": {

**Comment by moehreag** [comment]
I think the conflicts come from the fact that I put it through a json validator to not miss one again..

**Pull request closed without merging**
