### PR TITLE
Remove instant Overtime on 'Swamp' map

### PR DESCRIPTION
**Pull request by moehreag**
btw sock won in the first and only test

### CODE REVIEW

**Comment by Restioson** [comment]
Doesn't this make it go into instant overtime by changing the amount of time to 0?

**Comment by moehreag** [comment]
You may be right. I think I just looked at the wrong configurations for hints how to solve this..

**Comment by Restioson** [comment]
I'm not sure if there is a fix just from config to remove instant overtime. also, what do you mean by "instant"?

**Comment by moehreag** [comment]
> I'm not sure if there is a fix just from config to remove instant overtime. also, what do you mean by "instant"?
with 'instant' I mean that as soon the game is started, it goes into overtime..

**Comment by Restioson** [comment]
> with 'instant' I mean that as soon the game is started, it goes into overtime..

Sounds like something is misconfigured then

**Comment by Restioson** [comment]
The "time" property doesn't exist, you're looking for `time_limit_secs`.

**Comment by moehreag** [comment]
> The "time" property doesn't exist, you're looking for `time_limit_secs`.


Ok, thanks!

**Pull request merged**
